In [3]:
import numpy as np

In [4]:
a=np.array([1,2,3])
print(type(a), a.shape, a[0],a[1],a[2])
a[0]=5
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [6]:
b= np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
print(b.shape)
print(b[0,0], b[0,1], b[0,2])

(2, 3)
1 2 3


In [8]:
a=np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [9]:
a= np.ones((2,1))
print(a)

[[1.]
 [1.]]


In [10]:
a=np.full((1,2), 4)
print(a)

[[4 4]]


In [11]:
a=np.eye(2)
print(a)

[[1. 0.]
 [0. 1.]]


In [12]:
a= np.random.random((2,2))
print(a)

[[0.47741422 0.91842425]
 [0.50781616 0.68730152]]


In [14]:
a=np.array([[1,2,3,1],[4,5,6,2],[7,8,9,3]])
print(a)

[[1 2 3 1]
 [4 5 6 2]
 [7 8 9 3]]


In [16]:
b=a[:2, 1:3]
print(b)

[[2 3]
 [5 6]]


In [18]:
print(a[0,1])
b[0,0]=77
print(a[0,1])

2
77


In [21]:
c=a.reshape(6,2)
print(c)

[[ 1 77]
 [ 3  1]
 [ 4  5]
 [ 6  2]
 [ 7  8]
 [ 9  3]]
